packages:
  - apps/*
  - packages/*
nodeLinker: hoisted
allowBuilds:
  electron: true
  esbuild: true
  ssh2: true
  cpu-features: true
  electron-winstaller: false
minimumReleaseAgeExclude:
  - vite@8.3.3
